import { Photo } from '../interfaces';

export const photosData: Photo[] = [
  {
    id: 101,
    title: 'Malham Cove from above',
    description: '',
    image: 'malham-cove-from-above-1500.jpg',
    thumbnail: 'malham-cove-from-above-200.jpg',
  },
  {
    id: 102,
    title: 'Malham Cove Limestone pavement',
    description: '',
    image: 'malham-cove-limestone-pavement-1500.jpg',
    thumbnail: 'malham-cove-limestone-pavement-200.jpg',
  },
  {
    id: 103,
    title: 'Pen-y-ghent approach',
    description: '',
    image: 'pen-y-ghent-approach-1500.jpg',
    thumbnail: 'pen-y-ghent-approach-200.jpg',
  },
  {
    id: 104,
    title: 'Pen-y-ghent track',
    description: '',
    image: 'pen-y-ghent-track-1500.jpg',
    thumbnail: 'pen-y-ghent-track-200.jpg',
  },
  {
    id: 105,
    title: 'Settle Lambert Lane',
    description: '',
    image: 'settle-lambert-lane-1500.jpg',
    thumbnail: 'settle-lambert-lane-200.jpg',
  },
  {
    id: 106,
    title: 'Attermire Scar',
    description: '',
    image: 'attermire-scar-1500.jpg',
    thumbnail: 'attermire-scar-200.jpg',
  },
  {
    id: 107,
    title: 'Giggleswick Scar with Pen-y-ghent in the background',
    description: '',
    image: 'giggleswick-scar-pen-y-ghent-background-1500.jpg',
    thumbnail: 'giggleswick-scar-pen-y-ghent-background-200.jpg',
  },
  {
    id: 108,
    title: 'Inverse clouds above Langcliffe with Pen-y-ghent in the background',
    description: '',
    image: 'inverse-clouds-pen-y-ghent-1500.jpg',
    thumbnail: 'inverse-clouds-pen-y-ghent-200.jpg',
  },
  {
    id: 109,
    title: 'Approaching Attermire',
    description: '',
    image: 'approaching-attermire-1500.jpg',
    thumbnail: 'approaching-attermire-200.jpg',
  },
  {
    id: 110,
    title: 'Inverse Clouds, Settle, Craven',
    description: '',
    image: 'settle-craven-inverse-clouds-1500.jpg',
    thumbnail: 'settle-craven-inverse-clouds-200.jpg',
  },
  {
    id: 111,
    title: 'Langcliffe Inverse Clouds',
    description: '',
    image: 'langcliffe-inverse-clouds-1500.jpg',
    thumbnail: 'langcliffe-inverse-clouds-200.jpg',
  },
  {
    id: 112,
    title: 'Dales no name',
    description: '',
    image: 'dales-no-name-3-1500.jpg',
    thumbnail: 'dales-no-name-3-200.jpg',
  },
  {
    id: 113,
    title: 'Settle viewed from Castleberg',
    description: '',
    image: 'settle-from-castleberg-1500.jpg',
    thumbnail: 'settle-from-castleberg-200.jpg',
  },
  {
    id: 114,
    title: 'Pen-y-ghent',
    description: '',
    image: 'pen-y-ghent-sunshine-1500.jpg',
    thumbnail: 'pen-y-ghent-sunshine-200.jpg',
  },
  {
    id: 115,
    title: 'View off Ingleborough',
    description: '',
    image: 'ingleborough-1500.jpg',
    thumbnail: 'ingleborough-200.jpg',
  },
  {
    id: 116,
    title: 'Warrendale Knotts and Attermire',
    description: '',
    image: 'warrendale-knotts-attermire-1500.jpg',
    thumbnail: 'warrendale-knotts-attermire-200.jpg',
  },
  {
    id: 117,
    title: 'Dales no name',
    description: '',
    image: 'dales-no-name-2-1500.jpg',
    thumbnail: 'dales-no-name-2-200.jpg',
  },
  {
    id: 118,
    title: 'Dales no name',
    description: '',
    image: 'dales-no-name-1-1500.jpg',
    thumbnail: 'dales-no-name-1-200.jpg',
  },
  {
    id: 119,
    title: 'Pen-y-ghent approach',
    description: '',
    image: 'pen-y-ghent-close-1500.jpg',
    thumbnail: 'pen-y-ghent-close-200.jpg',
  },
  {
    id: 120,
    title: 'Attermire, sunshine',
    description: '',
    image: 'attermire-sunshine-1500.jpg',
    thumbnail: 'attermire-sunshine-200.jpg',
  },
  {
    id: 121,
    title: 'Cloudy Pen-y-ghent',
    description: '',
    image: 'pen-y-ghent-clouds-1500.jpg',
    thumbnail: 'pen-y-ghent-clouds-200.jpg',
  },
];
